# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            CODER
tagline:          'freelancer'
description:      'I am a freelancer for Web and APP development. Coding, coding, still coding. Reach me at <a href="https://github.com/kingofhawks" target="_blank">@kingofhawks</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'kingofhawks'
  url:            https://twitter.com/kingofhawks

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/kingofhawks/kingofhawks.github.io
